export const funFacts = {
  "basic_facts": {
    "favourite_colour": "jade",
    "favourite_season": "autumn because of the nostalgia and cosiness of it, and the colours but I'm much happier in the summer",
    "favourite_flower": "Baby's Breath",
    "favourite_animal": "sheep",
    "favourite_cuisine": "Thai",
    "favourite_film": "I dont watch a lot of movies but la la land is a favourite and childhood favourites are the little mermaid or pocahontas",
    "favourite_tv_show": "Daisy jones and the six, the good place, how I met your mother",
    "favourite_city": "Favourite place ive travelled to is Cairns or Budapest!",
    "dream_travel_destination": "Amazon rainforest",
    "Born_in": "Cambridge, UK",
    "currently_living_in": "Cambridge, UK",
    "tea_or_coffee": "Herbal teas",
    "favourite_drink": "Water",
    "favourite_food": "Spring rolls",
    "one_thing_to_eat_forever": "Caprese salad",
    "morning_person_or_night_owl": "morning person",
    "birthday": "2002-05-08",
  },
  "likes": [
    "plants",
    "interior design",
    "decorating",
    "art and crafts",
    "lino printing",
    "handmade objects",
    "jewellery",
    "warm and cosy spaces",
    "pretty but functional things",
    "unusual and individual things",
    "creative projects",
    "DIY projects",
    "things that are both clever and beautiful",
    "thrifting"
  ],
  "day_in_the_life": [
    "In office on Thursdays and Fridays, working from home on Mondays, Tuesdays and Wednesdays",
    "Lemon green tea and honey for breakfast with a slice of Jason's Protien sourdough bread",
    "Walk to work in the morning, listening to sad music",
    "Gym tuesdays and saturdays",
  ],
  "home_and_lifestyle": [
    "Likes having lots of plants around the house",
    "Wants a warm and personal home",
    "Prefers an interesting home over a perfectly minimalist one",
    "Enjoys decorating things herself",
    "Likes collecting things that have a story or personal significance",
    "Likes having creative projects to work on at home",
    "Would like space for hobbies and projects",
    "Appreciates good design in everyday objects"
  ],
  "personality": [
    "Curious",
    "Analytical",
    "Creative",
    "Independent",
    "Likes understanding how things work",
    "Likes being intellectually challenged",
    "Values competence",
    "Values authenticity",
    "Prefers straightforward people",
    "Does not particularly enjoy unnecessary formality",
    "Prefers honest answers over answers designed to sound nice",
    "Can overthink things when they matter",
    "Can get bored by repetitive or unnecessary bureaucracy",
    "Enjoys conversations beyond surface-level small talk",
    "Passionate about sustainability and environmental issues",
    "Loves animals and is vegetarian"
  ],
  "quirks": [
    "Can get disproportionately excited about small improvements to things",
    "Tends to turn random household problems into engineering projects",
    "Will investigate how something works rather than simply accepting it",
    "Likes finding clever DIY solutions",
    "Has both an analytical side and a creative/design side",
    "Often has several project ideas in progress or waiting to be started",
    "Likes things that are slightly nerdy without looking nerdy",
    "Enjoys making ordinary things unnecessarily interesting",
    "Is ambidextrous and can paint with both hands, and plays badminton with both hands",
    "Owns a guitar but cannot play it very well",
    "Believes engineering lacks empathy",
    "She has no sense of direction and gets lost easily",
    "She can make pots and other things on a potter's wheel",
    "She journals a lot and has a lot of notebooks",
    "She used to play as striker for a football team. She wasnt very good but she is left-footed.",
    "Eats an ungodly amount of tofu",
    "Can convert from binary to denary in her head and vice versa",
    "Tutors for Oxbridge entrance interviews and has a lot of experience with Oxbridge admissions",
  ],
  "values": [
    "Creativity",
    "Independence",
    "Competence",
    "Authenticity",
    "Thoughtfulness",
    "Dependability",
    "Having personal interests outside work",
    "Ambition without being performative"
  ],
}